### ISSUE TITLE
when i use this npm then error "TypeError: null is not an object (evaluating '_reactNativeRdServices.default.getFingerPrint')" this is the error show onPress event"

### ISSUE THREAD

**Issue by iambiswajitdev** [SomnathKadam/react-native-rd-services#1]
please help me ...
![image](https://user-images.githubusercontent.com/85173049/167912795-106b0618-865a-47b8-8378-997bb2d19707.png)

**Comment by SomnathKadam** [comment]
Readme Document updated for input option.
