### ISSUE TITLE
Mantra Device is not supporting in react-native-rd-services

### ISSUE THREAD

**Issue by daniel-19950** [SomnathKadam/react-native-rd-services#5]
While using these package react-native-rd-services, I tried to connect the Mantra Biometrice device with this package name "com.mantra.rdservice", it is not able to connect it and throwing error.

Code Example:-

import RdServices from "react-native-rd-services";
  let pidOption =
            "<?xml version='1.0'?><PidOptions ver='1.0'><Opts fCount='1' fType='2' iCount='0' pCount='0' format='0' pidVer='2.0' timeout='10000' posh='UNKNOWN' env='P' /><CustOpts></CustOpts></PidOptions>";

RdServices.getFingerPrint('com.mantra.rdservice', pidOption).then( (result)
    {
        const { status, message } = result;
        console.log('Status', status);
        console.log('Status', message);
    }
);

error :Giving Pid option undefined

**Comment by SomnathKadam** [comment]
You need to Pid option, Pid option given in readme document.

```
let pidOption =
            "<?xml version='1.0'?><PidOptions ver='1.0'><Opts fCount='1' fType='2' iCount='0' pCount='0' format='0' pidVer='2.0' timeout='10000' posh='UNKNOWN' env='P' /><CustOpts></CustOpts></PidOptions>";
```

**Comment by daniel-19950** [comment]
> You need to Pid option, Pid option given in readme document.
> 
> ```
> let pidOption =
>             "<?xml version='1.0'?><PidOptions ver='1.0'><Opts fCount='1' fType='2' iCount='0' pCount='0' format='0' pidVer='2.0' timeout='10000' posh='UNKNOWN' env='P' /><CustOpts></CustOpts></PidOptions>";
> ```

I have given the pid option still it is not working

**Comment by daniel-19950** [comment]
It is given error in the node modules package of rd services it is supporting only Stark ACPL Device.
I need to check multiple fingerprint devices.
