### ISSUE TITLE
how react native know rd device is connected

### ISSUE THREAD

**Issue by TSaiReddy** [SomnathKadam/react-native-rd-services#6]

**Comment by SomnathKadam** [comment]
In React Native,  does not have built-in knowledge of which rd-device is connected, similar to how it works in web development. However, you can pass a device type parameter to indicate the type of device you are targeting. This information is typically maintained in the readme file

**Comment by TSaiReddy** [comment]
I'm using StarTek fm220u (fingerprint scanner) and when I connect it to my Android device, and place my finger on my FP scanner, that result I need to see in my app. Please guide me

________________________________
